### ISSUE TITLE
Add new tolerations (NoExecute Exists) to the Daemonset

### ISSUE THREAD

**Issue by mmmarceleza** [caruccio/kubectl-plugins#1]
Master nodes from RKE2 clusters are provisioned with two Taints:

```yaml
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
```

With the current configuration, Pods from this Daemonset cannot be schedule on master nodes.

https://github.com/caruccio/kubectl-plugins/blob/056533f7fc540860228b7fa4140aa4dfeeeacc5f/kubectl-netcheck#L278
